backend:
  name: git-gateway
  branch: main
media_folder: "public/img/uploads"
public_folder: "/img/uploads"
site_url: https://schillergymnasium.netlify.app
display_url: https://schillergymnasium.netlify.app
locale: 'de'
collections: 
  - name: 'aktuelles'
    label: 'Aktuelles'
    folder: 'src/_aktuelles'
    create: true
    fields:
      - { name: 'title', label: 'Titel', widget: 'string'}
      - { name: 'shortTitle', label: 'Kurzer Titel', widget: 'string', required: false}
      - { name: 'date', label: 'Datum', widget: 'datetime' }
      - { name: 'author', label: 'Autor', widget: 'string'}
      - { name: 'description', label: 'Beschreibung', widget: string }
      - { name: 'banner', label: 'Vorschau Bild', widget: image }
      - { name: 'body', label: 'Inhalt', widget: markdown}
      - { name: 'tags', label: 'Tags',  widget: "list", default: ['post']}
  - name: "profil"
    label: "Profil"
    folder: "src/_pages/profil"
    create: true
    fields:
      - { name: 'title', label: 'Titel', widget: 'string' }
      - { name: 'shortTitle', label: 'Kurzer Titel', widget: 'string', required: false }
      - { name: 'titleUp', label: 'Titel Oben', widget: 'string', default: 'Profil' }
      - { name: 'titleDown', label: 'Titel Unten', widget: 'string', default: "am Schillergymnasium" }
      - { name: 'order', label: 'Reihenfolge in der Navigation', widget: 'number' }
      - { name: 'banners', label: 'Banner Bilder', widget: list, fields: [{ name: 'banner', label: 'Banner Bild', widget: image}, {name: 'alignment', label: 'Ausrichtung', widget: select, options: [{label: "Oben", value: "top"}, {label: "Mittig", value: "center"}, {label: "Unten", value: "bottom"}]}]}
      - { name: 'body', label: 'Inhalt', widget: markdown}
      - { name: 'tags', label: 'Tags', widget: list, default: ['profil', 'page'], required: false}
    sortableFields: ["order", "title"]
  - name: "personen"
    label: "Personen"
    folder: "src/_pages/personen"
    create: true
    fields:
      - { name: 'title', label: 'Titel', widget: 'string' }
      - { name: 'shortTitle', label: 'Kurzer Titel', widget: 'string', required: false }
      - { name: 'titleUp', label: 'Titel Oben', widget: 'string', default: 'Personen' }
      - { name: 'titleDown', label: 'Titel Unten', widget: 'string', default: "am Schillergymnasium" }
      - { name: 'order', label: 'Reihenfolge in der Navigation', widget: 'number' }
      - { name: 'banners', label: 'Banner Bilder', widget: list, fields: [{ name: 'banner', label: 'Banner Bild', widget: image}, {name: 'alignment', label: 'Ausrichtung', widget: select, options: [{label: "Oben", value: "top"}, {label: "Mittig", value: "center"}, {label: "Unten", value: "bottom"}]}]}
      - { name: 'body', label: 'Inhalt', widget: markdown}
      - { name: 'tags', label: 'Tags', widget: list, default: ['personen', 'page'], required: false}
    sortableFields: ["order", "title"]
  - name: "faecher"
    label: "Fächer"
    editor:
      preview: false
    folder: "src/_pages/fächer"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: 'title', label: 'Fach Title', widget: 'string' }
      - { name: 'titleDown', label: 'Titel Unten', widget: 'string', default: "am Schillergymnasium" }
      - { name: 'banners', label: 'Banner Bilder', widget: list, fields: [{ name: 'banner', label: 'Banner Bild', widget: image}, {name: 'alignment', label: 'Ausrichtung', widget: select, options: [{label: "Oben", value: "top"}, {label: "Mittig", value: "center"}, {label: "Unten", value: "bottom"}]}]}
      - {name: 'body', label: 'Über das Fach', widget: markdown}
      - {name: 'fachschaftGallery', label: 'Fachschaft Gallerie', widget: list, fields: [{ name: 'fachschaftImage', label: 'Bild', widget: image}]}
      - {name: 'tags', label: 'Tags', widget: list, default: ['fach'], required: false}
  - name: "faecher2"
    label: "Fächer"
    editor:
      preview: false
    folder: "src/_pages/faecher"
    create: true
    slug: "{{slug}}"
    fields:
      - {name: 'title', label: 'Fach Title', widget: 'string' }
      - { name: 'titleDown', label: 'Titel Unten', widget: 'string', default: "am Schillergymnasium" }
      - { name: 'banners', label: 'Banner Bilder', widget: list, fields: [{ name: 'banner', label: 'Banner Bild', widget: image}, {name: 'alignment', label: 'Ausrichtung', widget: select, options: [{label: "Oben", value: "top"}, {label: "Mittig", value: "center"}, {label: "Unten", value: "bottom"}]}]}
      - {name: 'body', label: 'Über das Fach', widget: markdown}
      - {name: 'fachschaftGallery', label: 'Fachschaft Gallerie', widget: list, fields: [{ name: 'fachschaftImage', label: 'Bild', widget: image}]}
      - {name: 'tags', label: 'Tags', widget: list, default: ['fach2'], required: false}
  - name: "lernen"
    label: "Lernen"
    editor:
      preview: false
    folder: "src/_pages/lernen"
    create: true
    fields:
      - { name: 'title', label: 'Titel', widget: 'string' }
      - { name: 'shortTitle', label: 'Kurzer Titel', widget: 'string', required: false }
      - { name: 'titleUp', label: 'Titel Oben', widget: 'string', default: 'Lernen' }
      - { name: 'titleDown', label: 'Titel Unten', widget: 'string', default: "am Schillergymnasium" }
      - { name: 'order', label: 'Reihenfolge in der Navigation', widget: 'number' }
      - { name: 'banners', label: 'Banner Bilder', widget: list, fields: [{ name: 'banner', label: 'Banner Bild', widget: image}, {name: 'alignment', label: 'Ausrichtung', widget: select, options: [{label: "Oben", value: "top"}, {label: "Mittig", value: "center"}, {label: "Unten", value: "bottom"}]}]}
      - { name: 'body', label: 'Inhalt', widget: markdown}
      - { name: 'tags', label: 'Tags', widget: list, default: ['lernen', 'page'], required: false}
      - { name: 'category', label: 'Kategorie',  widget: "string", default: 'Lernen'}
    sortableFields: ["order", "title"]
  - name: "schulleben"
    label: "Schulleben"
    editor:
      preview: false
    folder: "src/_pages/schulleben"
    create: true
    fields:
      - { name: 'title', label: 'Titel', widget: 'string' }
      - { name: 'shortTitle', label: 'Kurzer Titel', widget: 'string', required: false }
      - { name: 'titleUp', label: 'Titel Oben', widget: 'string', default: 'Schulleben' }
      - { name: 'titleDown', label: 'Titel Unten', widget: 'string', default: "am Schillergymnasium" }
      - { name: 'order', label: 'Reihenfolge in der Navigation', widget: 'number' }
      - { name: 'banners', label: 'Banner Bilder', widget: list, fields: [{ name: 'banner', label: 'Banner Bild', widget: image}, {name: 'alignment', label: 'Ausrichtung', widget: select, options: [{label: "Oben", value: "top"}, {label: "Mittig", value: "center"}, {label: "Unten", value: "bottom"}]}]}
      - {name: 'body', label: 'Inhalt', widget: markdown}
      - {name: 'tags', label: 'Tags', widget: list, default: ['schulleben', 'page'], required: false}
      - { name: 'category', label: 'Kategorie',  widget: "string", default: 'Schulleben'}
    sortableFields: ["order", "title"]
  - name: "service"
    label: "Service"
    editor:
      preview: false
    folder: "src/_pages/service"
    create: true
    fields:
      - { name: 'title', label: 'Titel', widget: 'string' }
      - { name: 'shortTitle', label: 'Kurzer Titel', widget: 'string', required: false }
      - { name: 'titleUp', label: 'Titel Oben', widget: 'string', default: 'Service' }
      - { name: 'titleDown', label: 'Titel Unten', widget: 'string', default: "am Schillergymnasium" }
      - { name: 'order', label: 'Reihenfolge in der Navigation', widget: 'number' }
      - { name: 'banners', label: 'Banner Bilder', widget: list, fields: [{ name: 'banner', label: 'Banner Bild', widget: image}, {name: 'alignment', label: 'Ausrichtung', widget: select, options: [{label: "Oben", value: "top"}, {label: "Mittig", value: "center"}, {label: "Unten", value: "bottom"}]}]}
      - {name: 'body', label: 'Inhalt', widget: markdown}
      - {name: 'tags', label: 'Tags', widget: list, default: ['service', 'page'], required: false}
    sortableFields: ["order", "title"]
  - name: "settings"
    label: "Settings"
    files: 
      - label: 'Startseite'
        name: 'home'
        file: 'src/_data/home.json'
        fields:
           - {label: 'Aktuelles Hintergrundbild', name: aktuellesBackground, widget: 'image'}
           - {label: 'Termine Hintergrundbild', name: termineBackground, widget: 'image'}
      - label: 'Anmeldephase'
        name: 'anmeldung'
        file: 'src/_data/anmeldung.json'
        fields:
           - {label: 'Ja/Nein', name: anmeldephase, widget: 'boolean', default: false}
           - {label: 'Nächstes Schuljahr', name: schuljahr, widget: string}
           - {label: 'Tags', name: 'tags', widget: 'list', default: ['anmeldung'], required: false }
      - label: 'Kontakt Einstellungen'
        name: 'contact'
        file: 'src/_data/contact.json'
        fields:
          - {label: 'Telefonnummer', name: phone, widget: 'string'}
          - {label: 'E-Mail Adresse', name: email, widget: string}
          - {label: 'Telefax', name: fax, widget: string}
          - {label: 'Tags', name: 'tags', widget: 'list', default: ['contact'], required: false }
      - label: 'Kontakt zu den Ehemaligen - Einstellungen'
        name: 'contactEhem'
        file: 'src/_data/contact_ehem.json'
        fields:
          - {label: 'Telefonnummer', name: phone, widget: 'string'}
          - {label: 'E-Mail Adresse', name: email, widget: string}
          - {label: 'Tags', name: 'tags', widget: 'list', default: ['contact'], required: false }


